version: '2'

volumes:
  postgres_data_dev: {}
  postgres_backup_dev: {}

services:
  postgres:
    build: ./compose/postgres
    image: koztay/istebu_dev_db
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data_dev  # volume data yerine data_dev yazdık bakalım olacak mı?
      - postgres_backup_dev:/backups
    environment:
      - POSTGRES_USER=ecommerce_istebu_cookiecutter

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    command: /start-dev.sh
    depends_on:
      - postgres
      - mailhog
    environment:
      - POSTGRES_USER=ecommerce_istebu_cookiecutter
      - USE_DOCKER=yes
      - DJANGO_ALLOWED_HOSTS=192.168.99.100
      - CELERY_BROKER_URL=redis://192.168.99.100:32768
      - REDIS_URL=redis://192.168.99.100:32768
    volumes:
      - .:/app
    ports:
      - "8000:8000"


  pycharm:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    depends_on:
      - postgres
    environment:
      - POSTGRES_USER=ecommerce_istebu_cookiecutter
    volumes:
      - .:/app

  redis:
    image: redis:latest

  mailhog:
    image: mailhog/mailhog
    ports:
      - "8025:8025"

# to run tasks on local development first run the redis on kitematic and update the ip/port of CELERY_BROKER_URL
# after that run the following command on terminal in the project folder:
# docker-compose -f dev.yml run django celery -A ecommerce_istebu_cookiecutter.taskapp worker -Q images,xml,default -l INFO -Ofair --concurrency=1 --without-gossip --without-mingle --without-heartbeat
