version: '3.1'

volumes:
  postgres_data: {}
  postgres_backup: {}
  static-data: {}

services:
  postgres:
    build: ./compose/postgres
    image: koztay/istebu_dev_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - postgres_backup:/backups
    env_file: .env_staging

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: istebu_cookicutter/django
    user: django
    depends_on:
      - postgres
      - redis
    volumes:
      - static-data:/static_root
    command: /gunicorn.sh
    env_file: .env_staging

  nginx:
    build: ./compose/nginx
    depends_on:
      - django
    volumes:
      - static-data:/static_root
    ports:
      - "0.0.0.0:80:80"
      - "0.0.0.0:443:443"


#  redis:
#    image: redis:latest

  redis:
    image: redis:latest


  celeryworker:
# Aşağıdakileri commentleyip yaratılmış imajı kullandırtmazsan yeniden djangoyu build ediyor. Çok saçma...
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
    image: istebu_cookicutter/django
    user: django
    env_file: .env_staging
    depends_on:
     - postgres
     - redis
    volumes:
      - static-data:/static_root
#    command: /celery.sh
#    command: celery multi start worker1 -A ecommerce_istebu_cookiecutter.taskapp -l INFO -Ofair --pidfile="/app/%n.pid" --logfile="/app/%n%I.log"
    command: celery -A ecommerce_istebu_cookiecutter.taskapp worker -Q images,xml,default -l INFO -Ofair --time-limit=300 --soft-time-limit=300 --without-gossip --without-mingle --without-heartbeat

  celerybeat:
# Aşağıdakileri commentleyip yaratılmış imajı kullandırtmazsan yeniden djangoyu build ediyor. Çok saçma...
#    build:
#      context: .
#      dockerfile: ./compose/django/Dockerfile
    image: istebu_cookicutter/django
    user: django
    env_file: .env_staging
    depends_on:
      - postgres
      - redis
    volumes:
      - static-data:/static_root
    command: celery -A ecommerce_istebu_cookiecutter.taskapp beat -l INFO -S django
# -S django parametresini koymazsan çalışmıyor periyodik tasklar...
