# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20170401_0112'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ('item__product__product_type__name',)},
        ),
    ]
