# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimportmap',
            name='dropping_words',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productimportmap',
            name='replace_words',
            field=models.TextField(blank=True, null=True),
        ),
    ]
