# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 15:47
from __future__ import unicode_literals

from django.db import migrations, models
import importer.models


class Migration(migrations.Migration):

    dependencies = [
        ('importer', '0002_auto_20170501_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(storage=importer.models.XMLFileSystemStorage('xml/upload'), upload_to='')),
                ('remote_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
