# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 20:33
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fields',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_field', models.CharField(blank=True, max_length=20, null=True)),
                ('xml_field', models.CharField(blank=True, max_length=1200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLImportMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Import edeceğimiz dosyaya ilişkin isim', max_length=120)),
                ('root', models.CharField(blank=True, help_text='Eğer XML dosyası ise o zaman ürünlerin çekileceği root tagi yaz.', max_length=120, null=True)),
                ('map', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Mapinfo')),
            ],
        ),
        migrations.AddField(
            model_name='fields',
            name='map',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_importer.XMLImportMap'),
        ),
    ]
