# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-08 10:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import my_importer.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(storage=my_importer.models.XMLFileSystemStorage('xml/upload'), upload_to='')),
                ('remote_url', models.URLField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLImportMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Import edeceğimiz dosyaya ilişkin isim', max_length=120)),
                ('root', models.CharField(blank=True, help_text='Eğer XML dosyası ise o zaman ürünlerin çekileceği root tagi yaz.', max_length=120, null=True)),
                ('remote_url', models.URLField(blank=True, null=True)),
                ('map', django.contrib.postgres.fields.jsonb.JSONField(verbose_name='Mapinfo')),
            ],
        ),
        migrations.AddField(
            model_name='importerfile',
            name='import_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_importer.XMLImportMap'),
        ),
    ]
