# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 22:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_importer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fields',
            name='map',
        ),
        migrations.AddField(
            model_name='xmlimportmap',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Fields',
        ),
    ]
