# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_importer', '0002_auto_20170401_0112'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImporterFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to='my_importer/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
