# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-01 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('my_importer', '0003_importerfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='importerfile',
            name='import_map',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='my_importer.XMLImportMap'),
        ),
        migrations.AddField(
            model_name='importerfile',
            name='remote_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
