# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-17 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-variation__inventory', 'id', 'title']},
        ),
    ]
