# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20170417_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='variation',
            name='gittigidiyor_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
        migrations.AddField(
            model_name='variation',
            name='n11_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20, null=True),
        ),
    ]
