# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 08:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20170419_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='buying_price_tl',
        ),
        migrations.RemoveField(
            model_name='variation',
            name='istebu_product_no',
        ),
    ]
