# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-27 08:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20170427_1132'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='istebu_product_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
