# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-17 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20170517_1635'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kargo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
