# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-06-05 09:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_auto_20170520_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='kargo_suresi',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
