# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-04 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_product_kargo_suresi'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='sub_title',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
