# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-10 08:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20170704_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='order',
            field=models.IntegerField(default=-1),
        ),
    ]
