# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-07-11 12:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_productimage_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'ordering': ('order',)},
        ),
    ]
